#####
##.##
.#...
=====
#####
##.##
.#...
; squares=20

* E F G I ; solutions=1
GGGII
GG.EI
.F...
=====
FEEEI
FF.EI
.F...
; Solution 1

* E G I M ; solutions=1
MEEEI
MM.II
.M...
=====
GGGEI
GG.EI
.M...
; Solution 1

* F G I N ; solutions=1
GGGNI
GG.NI
.F...
=====
FNNNI
FF.II
.F...
; Solution 1

* G I M N ; solutions=1
MNNNI
MM.NI
.M...
=====
GGGII
GG.NI
.M...
; Solution 1

; puzzles=4
; exitcode=0
