#####
#####
.####
###.#
; squares=18

* A B C I L ; solutions=2
* A B D G J ; solutions=2
* A B D G L ; solutions=2
* A B E F I ; solutions=2
* A B E F L ; solutions=2
* A B E H L ; solutions=2
* A B F G J ; solutions=1
* A B F H I ; solutions=1
* A B F H J ; solutions=2
* A B F H L ; solutions=1
* A B G H I ; solutions=2
* A B G H K ; solutions=1
* A C D G L ; solutions=1
* A C E H J ; solutions=1
* A C E H L ; solutions=2
* A C F G I ; solutions=2
* A C F G L ; solutions=1
* A C F H I ; solutions=2
* A C G H I ; solutions=2
* B C D G H ; solutions=1
; puzzles=20
; exitcode=0
