#####
#####
.####
###.#
; squares=18

* A B C I L ; solutions=2
ABBBI
ALLII
.LCCI
LLC.I
; Solution 1

AIIII
ALLIB
.LCCB
LLC.B
; Solution 2

* A B D G J ; solutions=2
AJJJJ
AJGGD
.GGDD
BBB.D
; Solution 1

BBBJJ
DDDGJ
.DGGJ
AAG.J
; Solution 2

* A B D G L ; solutions=2
LBBBA
LLLGA
.DLGG
DDD.G
; Solution 1

LBBBG
LLLGG
.DLGA
DDD.A
; Solution 2

* A B E F I ; solutions=2
FFFFA
IIIIA
.IEEE
BBB.E
; Solution 1

IIIIF
AAIEF
.EEEF
BBB.F
; Solution 2

* A B E F L ; solutions=2
EEEBF
ELLBF
.LABF
LLA.F
; Solution 1

EEELF
ELLLF
.LAAF
BBB.F
; Solution 2

* A B E H L ; solutions=2
AEEHH
AELHH
.ELLL
BBB.L
; Solution 1

EEEHH
EALHH
.ALLL
BBB.L
; Solution 2

* A B F G J ; solutions=1
GJJBF
GGJBF
.GJBF
AAJ.F
; Solution 1

* A B F H I ; solutions=1
HHIBF
HHIBF
.IIBF
AAI.F
; Solution 1

* A B F H J ; solutions=2
JJJJF
JAHHF
.AHHF
BBB.F
; Solution 1

JJJJF
JHHAF
.HHAF
BBB.F
; Solution 2

* A B F H L ; solutions=1
HHLLF
HHLAF
.LLAF
BBB.F
; Solution 1

* A B G H I ; solutions=2
AAHHI
GGHHI
.GGII
BBB.I
; Solution 1

HHAAI
HHGGI
.GGII
BBB.I
; Solution 2

* A B G H K ; solutions=1
HHGAA
HHGGB
.KKGB
KKK.B
; Solution 1

* A C D G L ; solutions=1
LAACC
LLLGC
.DLGG
DDD.G
; Solution 1

* A C E H J ; solutions=1
AJJHH
AEJHH
.EJCC
EEJ.C
; Solution 1

* A C E H L ; solutions=2
EEEHH
ELLHH
.LACC
LLA.C
; Solution 1

EEEHH
ELLHH
.LCCA
LLC.A
; Solution 2

* A C F G I ; solutions=2
IIIIF
AAIGF
.CGGF
CCG.F
; Solution 1

IIIIF
CCIGF
.CGGF
AAG.F
; Solution 2

* A C F G L ; solutions=1
CCAAF
CLLGF
.LGGF
LLG.F
; Solution 1

* A C F H I ; solutions=2
HHFAI
HHFAI
.CFII
CCF.I
; Solution 1

HHIAF
HHIAF
.CIIF
CCI.F
; Solution 2

* A C G H I ; solutions=2
CCHHI
CGHHI
.GGII
AAG.I
; Solution 1

HHICC
HHIGC
.IIGG
AAI.G
; Solution 2

* B C D G H ; solutions=1
HHBCC
HHBGC
.DBGG
DDD.G
; Solution 1

; puzzles=20
; exitcode=0
