#####
#####
.####
###.#
; squares=18

* A B F G J ; solutions=1
GJJBF
GGJBF
.GJBF
AAJ.F

* A B F H I ; solutions=1
HHIBF
HHIBF
.IIBF
AAI.F

* A B F H L ; solutions=1
HHLLF
HHLAF
.LLAF
BBB.F

* A B G H K ; solutions=1
HHGAA
HHGGB
.KKGB
KKK.B

* A C D G L ; solutions=1
LAACC
LLLGC
.DLGG
DDD.G

* A C E H J ; solutions=1
AJJHH
AEJHH
.EJCC
EEJ.C

* A C F G L ; solutions=1
CCAAF
CLLGF
.LGGF
LLG.F

* B C D G H ; solutions=1
HHBCC
HHBGC
.DBGG
DDD.G

; puzzles=8
; exitcode=0
